### ISSUE TITLE
Lexicographical Ordering of Keys

### ISSUE THREAD

**Issue by fabianhjr** [sunrise-choir/spec#1]
Hey, just wanted to add a suggestion to rather than leaving order unspecified, use lexicographical ordering of keys. (What is already done if they start with a number)

This would be way better for deserialized storage.

**Comment by AljoschaMeyer** [comment]
Make no mistake, the specified behavior is a horrible mess. But we can't change it anymore, it has to be preserved exactly for backwards-compatibility. A change as you suggested would break all old messages.

We will introduce a better format later, but for now the spec only describes stuff we can't change anymore.

**Comment by fabianhjr** [comment]
No, what I am saying is that there is a _legacy_ message which is the unspecified one and the new one you point me to from this repo. (Which only asks for numbered keys to be ordered lexicographically, specifically this part: https://github.com/sunrise-choir/spec/blob/master/src/datamodel.md#signing-encoding-objects)

**Comment by AljoschaMeyer** [comment]
Still not sure I get what you are saying. To recap what I *think* you communicate: "There is more than one way of encoding an object. It would be better if there wasn't." If that's not what you meant, please try to rephrase your concern again, so that my inflexible brain can catch up :smile:

`{ "type": "foo", "a": 0, "b": 0}` and  `{ "type": "foo", "b": 0, "a": 0}` are both valid encodings of the same content of a legacy message, resulting in different signing encodings (and thus signatures and hashes). In particular, there already exist hashes of messages that do not order their non-numeric-key entries lexicographically. So we can't retroactively enforce a bijection between logical values and encodings.

https://github.com/sunrise-choir/spec/blob/master/src/datamodel.md#signing-encoding :
> When receiving a message over the network, the order of the freely-orderable object entries in the transport encoding is the order that must be used for verifying the signature. Thus the network encoding induces a unique signing encoding to use for signature checking.

**Comment by fabianhjr** [comment]
Yeah, but as far as I understand this spec is that it is a revised spec so more than changing legacy signatures it would be to enforce an order on the new encodings.

**Comment by AljoschaMeyer** [comment]
So far the spec is purely descriptive. The new stuff will be added later (once it exists). The plan is to migrate to a data format that covers more types (e.g. integers) and has a single canonical encoding per value (see the #hsdt channel on ssb).

**Comment by fabianhjr** [comment]
Oh, sorry then I misunderstood. Will definitely look trough the HSDT channel. :3

Thanks for the help.
